---
version: '3.7'
services:

  bldr:
    image: maven:alpine
    volumes:
      - ./web/src:/tmp/src
    working_dir: /tmp/src
    command: >
      bash -c "apk --no-cache add git &&
               git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git &&
               mvn -T 1C -Dmaven.test.skip clean package -f boxfuse-sample-java-war-hello &&
               cp boxfuse-sample-java-war-hello/target/hello-1.0.war . &&
               rm -rf boxfuse-sample-java-war-hello"

  web:
    build: web
#    pull_policy: never
    image: evg33/hw07web:0.0.8
    depends_on:
      - bldr
    ports:
      - "80:8080"
