---
version: '3.7'
services:

  buildapp:
    build: build
    volumes:
      - 'myshare:/shared'
    image: evg33/hw07bld:0.0.5
    pull_policy: never

  web:
    build: web
    volumes:
      - 'myshare:/shared:ro'
    image: evg33/hw07web:0.0.5
    pull_policy: never
    depends_on:
      - buildapp
    ports:
      - "80:8080"

volumes:
  myshare:
    driver: local
