---
version: '2'
services:

  compiler:
    build: compiler
    image: evg33/test07cmp
    volumes:
      - war:/app

  web:
    build: tomcat
    image: evg33/tes07web
    depends_on:
      - compiler
    ports:
      - "80:8080"
    volumes:
      - war:/opt

volumes:
  war:
